### ISSUE TITLE
Incompatibilities with Internet Explorer 8

### ISSUE THREAD

**Issue by rmartony** [okfn/bubbletree#12]
I don't know if bubbletree is meant to run in Internet Explorer 8 but it is not working in openspending.

Details of error:

Message: Expected identifier
Line: 37
Character: 36
Code: 0
URI: http://openspending.org/static/js/model.js

Message: Object doesn't support this property or method
Line: 50
Character: 5
Code: 0
URI: http://openspending.org/static/app/explorer-v2/js/explorer.js

Example dataset used to reproduce the problem (could be any):

http://openspending.org/city_of_bochum_expenditure/explorer

**Comment by pwalsh** [comment]
CLOSING. OLD. IE8 is almost dead.
