### ISSUE TITLE
3rd Level children notworking

### ISSUE THREAD

**Issue by greales** [okfn/bubbletree#26]
Hi Bubbletree developers,

  i'm working on a 3rd level bubble but i could not seem to make it work below is the 3rd level script that i did. is there something wrong that i did? please help.

Thanks in advance...

$(function() {
            var data = {
                label: 'Total',
                amount: 120,
                children: [
                    { label: '1rst Level', amount: 30, color: '#D95F02',
                        children: [
                        { label: 'Dingen', amount: 15, color: '#D95F02' },
                        { label: 'Stuff', amount: 15, color: '#D95F02' }
                    ] },
                    { label: '2nd Level', amount: 40, color: '#1B9E77',
					    children: [
						{ label: 'Sub2', amount: 20, color: '#cccccc' },
						{ label: 'Sub2', amount: 20, color: '#cccccc' }
								   ]
					},                    
					{ label: '3rd Level', amount: 30, color: '#7570B3',
                        children: [
                        { label: 'Bananen', amount: 15, color: '#7570B3',
						   children: [
							 { label: 'glenn', amount: 10, color: '#7570B3' },
							 { label: 'glenn', amount: 5, color: '#7570B3' }							 
						             ]
						},
                        { label: 'Pyjamas', amount: 15, color: '#7570B3',
						   children: [
							  { label: 'mark', amount: 5, color: '#000000' },
							  { label: 'reales', amount: 10, color: '#cccccc' }
						             ]
						}
                                ]
                    }
                ]
            };

            new BubbleTree({
                data: data,
                bubbleType: 'donut',
                container: '.bubbletree'
            });

        });

**Comment by ttrapp** [comment]
The Bubbletree has to have a special property. You can draw it if the amount of a note is the sum of the amounts of its adjacent nodes.

**Comment by pwalsh** [comment]
CLOSING. OLD.
