### ISSUE TITLE
Tooltip problem

### ISSUE THREAD

**Issue by greales** [okfn/bubbletree#28]
Hi All,

i'm new in this environment and trying to make a icon and Tooltip text combination when hovered. below is the sample link that i'm working on

http://ejeepney.org/adaptracker/bubbletree-master/sample-other-2.html

would it be possible to have a text popping when you hover your mouse on one of the SVG icon? with my current setup. something like this http://wheredoesmymoneygo.org/bubbletree-map.html#/~/total/running-the-country--social-systems/transport

if you can point me to the right direction that would be a great help.

many thanks

**Comment by pwalsh** [comment]
Dup of #31
