### ISSUE TITLE
why not bower?

### ISSUE THREAD

**Issue by duxiaofeng-github** [okfn/bubbletree#37]

**Comment by pwalsh** [comment]
Hi @duxiaofeng-github we can do that, yes. We just did not do it as we don't use bower.

**Comment by mbrk** [comment]
forked and added: https://github.com/mbrk/bubbletree

`bower install bubbletree-bowerized`

**Comment by pwalsh** [comment]
@mbrk great! Instead of hard forking and publishing your own, it would be great if you would do a PR on the canonical repository instead (i.e.: this one), so we can publish to both npm and bower going forward.

Is there any reason why you are not doing this?

**Comment by mbrk** [comment]
Nope, just wasn't sure if this was welcome. Therefore i used a specific name. Will do a PR.

**Comment by mbrk** [comment]
https://github.com/okfn/bubbletree/pull/43

**Comment by pwalsh** [comment]
Thanks @mbrk it is very very welcome.

**Comment by mbrk** [comment]
please adjust the readme (in the end it says: "in this fork..."), and publish in bower with the correct endpoint.  `$ bower register <my-package-name> <git-endpoint>`

**Comment by pwalsh** [comment]
@mbrk done, thank you.

**Comment by mbrk** [comment]
great!
