### ISSUE TITLE
Turn BubbleTree documenation into proper jekyll site

### ISSUE THREAD

**Issue by gka** [okfn/bubbletree#7]
Namely we should

* completely remove demos and docs from ``master`` 
* completely remove sources from ``gh-pages``
* create (or possibly re-use) a clean and good-looking site template
* include a showcase of real-world [use cases](https://github.com/okfn/bubbletree/issues/6#issuecomment-4469868) (e.g. guardian) 
* include tutorials and link to those written by others

**Comment by pwalsh** [comment]
WONT FIX. Need to do something, but not this.
